WIP: PV boards
jhonnold/node-tlcv pull request #49
Opened 2023-06-30 17:12 UTC by tsoj

I tried adding PV preview boards. It currently looks like this:
![node-tlcv_with_pv_boards](https://github.com/jhonnold/node-tlcv/assets/17938103/04c8d80f-eef0-4646-8c50-8dfeceb7c1c9)

However, on small screens it looks bad. I haven't found a good way to automatically scale the PV boards. Generally, this is my first attempt doing the javascript stuff. I assume some of this code is a bit bad, so I appreciate any feedback.

2023-07-05 02:32 UTC, jhonnold commented
I have not been ignoring this, I've been in the mountains for the last 5 days. I'll take a look at this.

2023-07-07 00:29 UTC, jhonnold requested changes
Thanks for your work on this! I've left comments that I think need to be addressed. If you don't want to do these, I will (because this is a nice feature to have), just let me know!

2023-07-07 00:29 UTC, jhonnold commented on src/broadcast.ts
> +  blackPvFen: string;
I think these make more sense as a part of the `SerializedGame` type.

2023-07-07 00:29 UTC, jhonnold commented on src/chess-game.ts
> +  }
I think this is something that we should calculate when a PV is received (only when it's your turn) and cached, rather than at serialization time.

2023-07-07 00:29 UTC, jhonnold commented on views/info-card.ejs
> +  </div>
Default styling for the dark theme will need the rounded edges made less aggressive.

2023-07-07 00:29 UTC, jhonnold commented on public/js/main.js
> +  const pvBoardWhite = Chessboard('white-pvBoard', { pieceTheme: '/img/{piece}.svg', showNotation: false });
If there is a way to disable animations we might want to to prevent pieces flying around as PV comes in quickly.

2023-07-07 22:39 UTC, tsoj commented
I think I solved the issues. I put the pvFen into the Player/SerializedPlayer, as that made the most sense to me, even though it kind of depends on the game.

2023-07-08 16:33 UTC, jhonnold commented
I like where this is at, apart from the styling and really awkward JS adjustment of styling info-cards + pv boards. I'm thinking it's possible to just lock the pv-board at 155x155 or something along those lines and work from there.

I'm going to try and merge this without the UI in place yet, and will see if I can adjust the PV board styling more.

2023-07-08 16:55 UTC, merged