Display 7-man tablebase result
jhonnold/node-tlcv pull request #51
Opened 2023-07-06 13:12 UTC by ianagbip1oti

This uses the same text box as the Opening, and will Display "Tablebase: White Win" (or Draw or Black Win) as appropriate.

2023-07-06 13:12 UTC, ianagbip1oti commented on src/chess-game.ts
> +    for (let i = 0; i < board.length; i++) {
I feel like there has to be a better way to do this. I couldn't find it yet tho.

2023-07-07 00:43 UTC, jhonnold requested changes

2023-07-07 00:43 UTC, jhonnold commented on src/chess-game.ts
> +    }
Outbound TPS should be low enough where it probably doesn't hurt to always call lichess.

2023-07-07 00:43 UTC, jhonnold commented on src/chess-game.ts
> +  category: string | null;
Rather than overloading this type for different APIs, I would probably rename it for the opening API and then define another for the tablebase API.

2023-07-07 00:43 UTC, jhonnold commented on src/handler.ts
> +      this._game.setTablebase();
Move this to outside the whole `if` statement. Otherwise, if the move is failed to be parsed, the TB call won't happen.

2023-07-10 13:13 UTC, merged